
public class ChangePhoneForm extends javax.swing.JFrame {

    /**
     * Creates new form ChangeTel
     */
    public ChangePhoneForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ChangePhone = new javax.swing.JLabel();
        lbl_Phone = new javax.swing.JLabel();
        btn_Cancel = new javax.swing.JButton();
        btn_Ok = new javax.swing.JButton();
        txt_TelPhone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(546, 293));
        setResizable(false);
        setSize(new java.awt.Dimension(546, 293));
        getContentPane().setLayout(null);

        lbl_ChangePhone.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_ChangePhone.setText("Change Phone");
        getContentPane().add(lbl_ChangePhone);
        lbl_ChangePhone.setBounds(190, 50, 190, 50);

        lbl_Phone.setText("New Phone :");
        getContentPane().add(lbl_Phone);
        lbl_Phone.setBounds(140, 130, 80, 14);

        btn_Cancel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cancel.setText("Cancel");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Cancel);
        btn_Cancel.setBounds(360, 170, 80, 25);

        btn_Ok.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Ok.setForeground(new java.awt.Color(255, 255, 255));
        btn_Ok.setText("OK");
        btn_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OkActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Ok);
        btn_Ok.setBounds(290, 170, 60, 25);

        txt_TelPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_TelPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TelPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(txt_TelPhone);
        txt_TelPhone.setBounds(220, 120, 220, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TelPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TelPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TelPhoneActionPerformed

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        // TODO add your handling code here:
        ProfileService.showProfileForm();
        this.hide();
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void btn_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OkActionPerformed
        // TODO add your handling code here:
        User user = ProfileService.getUser(LoginForm.userCurrent);
        String phone = txt_TelPhone.getText();
        if(ProfileService.checkNull(phone)&&ProfileService.checkLengthPhone(phone)&&ProfileService.checkFristNumber(phone)){
            ProfileService.changePhone(user,phone);
            ProfileService.showProfileForm();
            this.hide();
        }else{
            txt_TelPhone.setText("");
        }
    }//GEN-LAST:event_btn_OkActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Ok;
    private javax.swing.JLabel lbl_ChangePhone;
    private javax.swing.JLabel lbl_Phone;
    private javax.swing.JTextField txt_TelPhone;
    // End of variables declaration//GEN-END:variables
}
