
public class ChangeAddressForm extends javax.swing.JFrame {

    /**
     * Creates new form ChangeAddress
     */
    public ChangeAddressForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ChangeAddress = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        btn_Ok = new javax.swing.JButton();
        btn_Cancel = new javax.swing.JButton();
        txt_NameAddress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(546, 293));
        setResizable(false);
        setSize(new java.awt.Dimension(546, 293));
        getContentPane().setLayout(null);

        lbl_ChangeAddress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_ChangeAddress.setText("Change Address");
        getContentPane().add(lbl_ChangeAddress);
        lbl_ChangeAddress.setBounds(170, 60, 190, 29);

        lbl_address.setText("New Address :");
        getContentPane().add(lbl_address);
        lbl_address.setBounds(130, 130, 70, 14);

        btn_Ok.setBackground(new java.awt.Color(34, 167, 240));
        btn_Ok.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Ok.setForeground(new java.awt.Color(255, 255, 255));
        btn_Ok.setText("OK");
        btn_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OkActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Ok);
        btn_Ok.setBounds(290, 170, 60, 25);

        btn_Cancel.setBackground(new java.awt.Color(255, 0, 0));
        btn_Cancel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cancel.setText("Cancel");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Cancel);
        btn_Cancel.setBounds(360, 170, 80, 25);

        txt_NameAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_NameAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NameAddressActionPerformed(evt);
            }
        });
        getContentPane().add(txt_NameAddress);
        txt_NameAddress.setBounds(220, 120, 220, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        // TODO add your handling code here:
        ProfileService.showProfileForm();
        this.hide();
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void txt_NameAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NameAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NameAddressActionPerformed

    private void btn_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OkActionPerformed
        User user = ProfileService.getUser(LoginForm.userCurrent);
        String address = txt_NameAddress.getText();
        if(ProfileService.checkNull(address)){
            ProfileService.changeAddress(user,address);
            ProfileService.showProfileForm();
            this.hide();
        }
    }//GEN-LAST:event_btn_OkActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Ok;
    private javax.swing.JLabel lbl_ChangeAddress;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JTextField txt_NameAddress;
    // End of variables declaration//GEN-END:variables
}
